---
version: '3.5'

services:
  db:
    image: postgres:10
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}

  # sadly all this extra stuff is neccessary in the current version
  ttrss:
    image: x86dev/docker-ttrss
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - DB_ENV_PASS=${ENV_POSTGRES_PASSWORD}
      - DB_ENV_USER=postgres
      - DB_HOST=db
      - DB_NAME=ttrss
      - DB_PASS=${ENV_TTRSS_DB_PASS}
      - DB_PORT=tcp://db:5432
      - DB_PORT_5432_TCP=tcp://db:5432
      - DB_PORT_5432_TCP_ADDR=db
      - DB_PORT_5432_TCP_PORT=5432
      - DB_PORT_5432_TCP_PROTO=tcp
      - DB_USER=ttrss
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}
      - SELF_URL_PATH=https://ttrss.gnaswelt.de/
      - TTRSS_PORT=8080
      - TTRSS_SELF_URL=https://ttrss.gnaswelt.de/
      # - TTRSS_PROTO=http
      - TTRSS_URL=ttrss.gnaswelt.de
      - VIRTUAL_HOST=ttrss.gnaswelt.de
      - VIRTUAL_PORT=8080
    depends_on:
      - db
    networks:
      - proxy-tier
      - default
  
  app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_PASSWORD=${ENV_NEXTCLOUD_ADMIN_PASSWORD}
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
    depends_on:
      - db

  web:
    image: nginx
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
      - ./nextcloud/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VIRTUAL_HOST=gnaswelt.de
      - LETSENCRYPT_HOST=gnaswelt.de,ttrss.gnaswelt.de
      - LETSENCRYPT_EMAIL=${ENV_LETSENCRYPT_EMAIL}
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nextcloud/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

        #  collabora:
        #    image: collabora/code
        #    expose:
        #      - 9980
        #    cap_add:
        #      - MKNOD
        #    environment:
        #      - domain=collabora.gnaswelt.de
        #      - VIRTUAL_HOST=collabora.gnaswelt.de
        #      - VIRTUAL_NETWORK=nginx-proxy
        #      - VIRTUAL_PORT=9980
        #      - VIRTUAL_PROTO=https
        #      - LETSENCRYPT_HOST=collabora.gnaswelt.de
        #    networks:
        #      - proxy-tier

volumes:
  db:
  nextcloud:
  certs:
  conf.d:
  vhost.d:
  html:

networks:
  proxy-tier:
