---
version: '3.5'

services:
  app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_PASSWORD=${ENV_NEXTCLOUD_ADMIN_PASSWORD}
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres_db
      - NEXTCLOUD_ADMIN_USER=admin
    networks:
      - default

  web:
    image: nginx
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
      - ./nextcloud/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VIRTUAL_HOST=gnaswelt.de
      - LETSENCRYPT_HOST=gnaswelt.de,ttrss.gnaswelt.de,gitlab.gnaswelt.de
      - LETSENCRYPT_EMAIL=${ENV_LETSENCRYPT_EMAIL}
    depends_on:
      - app
    networks:
      - default
      - nginx-proxy_default

volumes:
  nextcloud:

networks:
  nginx-proxy_default:
    external: true
  postgres_default:
    external: true
