---
version: '3.5'

services:
  db:
    image: postgres:10
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

networks:
  postgre:
