---
version: '3.1'

services:
  teamspeak:
    deploy:
      resources:
        reservations:
          cpus: "0.3"
    image: teamspeak
    restart: always
    volumes:
      - /opt/ts3server:/var/ts3server
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_LICENSE: accept
      LETSENCRYPT_HOST: gnaswelt.de,ttrss.gnaswelt.de,gitlab.gnaswelt.de
      LETSENCRYPT_EMAIL: ${ENV_LETSENCRYPT_EMAIL}
    networks:
      - default

