---
version: '3.5'

services:
  ttrss:
    image: x86dev/docker-ttrss
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - DB_ENV_PASS=${ENV_POSTGRES_PASSWORD}
      - DB_ENV_USER=postgres
      - DB_HOST=postgres_db
      - DB_NAME=ttrss
      - DB_PASS=${ENV_TTRSS_DB_PASS}
      - DB_PORT=tcp://postgres_db:5432
      - DB_PORT_5432_TCP=tcp://postgres_db:5432
      - DB_PORT_5432_TCP_ADDR=db
      - DB_PORT_5432_TCP_PORT=5432
      - DB_PORT_5432_TCP_PROTO=tcp
      - DB_USER=ttrss
      - POSTGRES_PASSWORD=${ENV_POSTGRES_PASSWORD}
      - SELF_URL_PATH=https://ttrss.gnaswelt.de/
      - TTRSS_PORT=8080
      - TTRSS_SELF_URL=https://ttrss.gnaswelt.de/
      # - TTRSS_PROTO=http
      - TTRSS_URL=ttrss.gnaswelt.de
      - VIRTUAL_HOST=ttrss.gnaswelt.de
      - VIRTUAL_PORT=8080
    depends_on:
      - db
    networks:
      - postgres_default
      - nginx-proxy_default

volumes:
  postgres_db:
    external: true
networks:
  nginx-proxy_default:
    external: true
  postgres_default:
    external: true
